<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Direction_gen extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Direction_gen_model');
    } 

    /*
     * Listing of direction_gen
     */
    function index()
    {
        $data['direction_gen'] = $this->Direction_gen_model->get_all_direction_gen();
        
        $data['_view'] = 'direction_gen/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new direction_gen
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('NOM_COMPLET','NOM COMPLET','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'NOM_COMPLET' => $this->input->post('NOM_COMPLET'),
				'SIGNATURE_DG' => $this->input->post('SIGNATURE_DG'),
				'DATE_SIGNATURE' => $this->input->post('DATE_SIGNATURE'),
				'DATE_MODIFICATION' => $this->input->post('DATE_MODIFICATION'),
				'DATE_SUPPRESSION' => $this->input->post('DATE_SUPPRESSION'),
            );
            
            $direction_gen_id = $this->Direction_gen_model->add_direction_gen($params);
            redirect('direction_gen/index');
        }
        else
        {            
            $data['_view'] = 'direction_gen/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a direction_gen
     */
    function edit($ID)
    {   
        // check if the direction_gen exists before trying to edit it
        $data['direction_gen'] = $this->Direction_gen_model->get_direction_gen($ID);
        
        if(isset($data['direction_gen']['ID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('NOM_COMPLET','NOM COMPLET','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'NOM_COMPLET' => $this->input->post('NOM_COMPLET'),
					'SIGNATURE_DG' => $this->input->post('SIGNATURE_DG'),
					'DATE_SIGNATURE' => $this->input->post('DATE_SIGNATURE'),
					'DATE_MODIFICATION' => $this->input->post('DATE_MODIFICATION'),
					'DATE_SUPPRESSION' => $this->input->post('DATE_SUPPRESSION'),
                );

                $this->Direction_gen_model->update_direction_gen($ID,$params);            
                redirect('direction_gen/index');
            }
            else
            {
                $data['_view'] = 'direction_gen/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The direction_gen you are trying to edit does not exist.');
    } 

    /*
     * Deleting direction_gen
     */
    function remove($ID)
    {
        $direction_gen = $this->Direction_gen_model->get_direction_gen($ID);

        // check if the direction_gen exists before trying to delete it
        if(isset($direction_gen['ID']))
        {
            $this->Direction_gen_model->delete_direction_gen($ID);
            redirect('direction_gen/index');
        }
        else
            show_error('The direction_gen you are trying to delete does not exist.');
    }
    
}
