<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Directeur_financier extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Directeur_financier_model');
    } 

    /*
     * Listing of directeur_financier
     */
    function index()
    {
        $data['directeur_financier'] = $this->Directeur_financier_model->get_all_directeur_financier();
        
        $data['_view'] = 'directeur_financier/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new directeur_financier
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('NOM_COMPLET','NOM COMPLET','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'NOM_COMPLET' => $this->input->post('NOM_COMPLET'),
				'SIGNATURE_DAF' => $this->input->post('SIGNATURE_DAF'),
				'DATE_CREATION' => $this->input->post('DATE_CREATION'),
				'DATE_MODIFICATION' => $this->input->post('DATE_MODIFICATION'),
				'DATE_SUPPRESSION' => $this->input->post('DATE_SUPPRESSION'),
            );
            
            $directeur_financier_id = $this->Directeur_financier_model->add_directeur_financier($params);
            redirect('directeur_financier/index');
        }
        else
        {            
            $data['_view'] = 'directeur_financier/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a directeur_financier
     */
    function edit($ID)
    {   
        // check if the directeur_financier exists before trying to edit it
        $data['directeur_financier'] = $this->Directeur_financier_model->get_directeur_financier($ID);
        
        if(isset($data['directeur_financier']['ID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('NOM_COMPLET','NOM COMPLET','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'NOM_COMPLET' => $this->input->post('NOM_COMPLET'),
					'SIGNATURE_DAF' => $this->input->post('SIGNATURE_DAF'),
					'DATE_CREATION' => $this->input->post('DATE_CREATION'),
					'DATE_MODIFICATION' => $this->input->post('DATE_MODIFICATION'),
					'DATE_SUPPRESSION' => $this->input->post('DATE_SUPPRESSION'),
                );

                $this->Directeur_financier_model->update_directeur_financier($ID,$params);            
                redirect('directeur_financier/index');
            }
            else
            {
                $data['_view'] = 'directeur_financier/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The directeur_financier you are trying to edit does not exist.');
    } 

    /*
     * Deleting directeur_financier
     */
    function remove($ID)
    {
        $directeur_financier = $this->Directeur_financier_model->get_directeur_financier($ID);

        // check if the directeur_financier exists before trying to delete it
        if(isset($directeur_financier['ID']))
        {
            $this->Directeur_financier_model->delete_directeur_financier($ID);
            redirect('directeur_financier/index');
        }
        else
            show_error('The directeur_financier you are trying to delete does not exist.');
    }
    
}
