<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Agent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get agent by ID
     */
    function get_agent($ID)
    {
        return $this->db->get_where('agent',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all agent
     */
    function get_all_agent()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('agent')->result_array();
    }
        
    /*
     * function to add new agent
     */
    function add_agent($params)
    {
        $this->db->insert('agent',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update agent
     */
    function update_agent($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('agent',$params);
    }
    
    /*
     * function to delete agent
     */
    function delete_agent($ID)
    {
        return $this->db->delete('agent',array('ID'=>$ID));
    }
}
