<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bon_de_commande_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bon_de_commande by ID
     */
    function get_bon_de_commande($ID)
    {
        return $this->db->get_where('bon_de_commande',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all bon_de_commande
     */
    function get_all_bon_de_commande()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('bon_de_commande')->result_array();
    }
        
    /*
     * function to add new bon_de_commande
     */
    function add_bon_de_commande($params)
    {
        $this->db->insert('bon_de_commande',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bon_de_commande
     */
    function update_bon_de_commande($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('bon_de_commande',$params);
    }
    
    /*
     * function to delete bon_de_commande
     */
    function delete_bon_de_commande($ID)
    {
        return $this->db->delete('bon_de_commande',array('ID'=>$ID));
    }
}
