<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chef_departement_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get chef_departement by ID
     */
    function get_chef_departement($ID)
    {
        return $this->db->get_where('chef_departement',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all chef_departement
     */
    function get_all_chef_departement()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('chef_departement')->result_array();
    }
        
    /*
     * function to add new chef_departement
     */
    function add_chef_departement($params)
    {
        $this->db->insert('chef_departement',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update chef_departement
     */
    function update_chef_departement($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('chef_departement',$params);
    }
    
    /*
     * function to delete chef_departement
     */
    function delete_chef_departement($ID)
    {
        return $this->db->delete('chef_departement',array('ID'=>$ID));
    }
}
