<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Directeur_financier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get directeur_financier by ID
     */
    function get_directeur_financier($ID)
    {
        return $this->db->get_where('directeur_financier',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all directeur_financier
     */
    function get_all_directeur_financier()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('directeur_financier')->result_array();
    }
        
    /*
     * function to add new directeur_financier
     */
    function add_directeur_financier($params)
    {
        $this->db->insert('directeur_financier',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update directeur_financier
     */
    function update_directeur_financier($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('directeur_financier',$params);
    }
    
    /*
     * function to delete directeur_financier
     */
    function delete_directeur_financier($ID)
    {
        return $this->db->delete('directeur_financier',array('ID'=>$ID));
    }
}
