<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Direction_gen_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get direction_gen by ID
     */
    function get_direction_gen($ID)
    {
        return $this->db->get_where('direction_gen',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all direction_gen
     */
    function get_all_direction_gen()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('direction_gen')->result_array();
    }
        
    /*
     * function to add new direction_gen
     */
    function add_direction_gen($params)
    {
        $this->db->insert('direction_gen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update direction_gen
     */
    function update_direction_gen($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('direction_gen',$params);
    }
    
    /*
     * function to delete direction_gen
     */
    function delete_direction_gen($ID)
    {
        return $this->db->delete('direction_gen',array('ID'=>$ID));
    }
}
