<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fiche_de_besoin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fiche_de_besoin by ID
     */
    function get_fiche_de_besoin($ID)
    {
        return $this->db->get_where('fiche_de_besoin',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all fiche_de_besoin
     */
    function get_all_fiche_de_besoin()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('fiche_de_besoin')->result_array();
    }
        
    /*
     * function to add new fiche_de_besoin
     */
    function add_fiche_de_besoin($params)
    {
        $this->db->insert('fiche_de_besoin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fiche_de_besoin
     */
    function update_fiche_de_besoin($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('fiche_de_besoin',$params);
    }
    
    /*
     * function to delete fiche_de_besoin
     */
    function delete_fiche_de_besoin($ID)
    {
        return $this->db->delete('fiche_de_besoin',array('ID'=>$ID));
    }
}
