<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Service_gen_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get service_gen by ID
     */
    function get_service_gen($ID)
    {
        return $this->db->get_where('service_gen',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all service_gen
     */
    function get_all_service_gen()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('service_gen')->result_array();
    }
        
    /*
     * function to add new service_gen
     */
    function add_service_gen($params)
    {
        $this->db->insert('service_gen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update service_gen
     */
    function update_service_gen($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('service_gen',$params);
    }
    
    /*
     * function to delete service_gen
     */
    function delete_service_gen($ID)
    {
        return $this->db->delete('service_gen',array('ID'=>$ID));
    }
}
